version: '2'

volumes:
    cache:
        driver: local
        driver_opts:
            type: tmpfs
            device: tmpfs
            o: uid=33
    logs:
        driver: local
        driver_opts:
            type: tmpfs
            device: tmpfs
            o: uid=33

services:

    root:
        image: php:fpm
        volumes:
            - ./src/root:/var/www/html

    site1:
        image: php:fpm
        volumes:
            - ./src/site1:/var/www/html

    site2:
        image: php:fpm
        volumes:
            - ./src/site2:/var/www/html

    site3:
        image: php:fpm
        volumes:
            - ./src/site3:/var/www/html

    nginx:
        image: nginx:latest
        ports:
            - "8080:80"
        depends_on:
            - root
            - site1
            - site2
            - site3
        volumes:
            - ./etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

