version: '2'

volumes:
    cache:
        driver: local
        driver_opts:
            type: tmpfs
            device: tmpfs
            o: uid=33
    logs:
        driver: local
        driver_opts:
            type: tmpfs
            device: tmpfs
            o: uid=33

services:

    website:
        build:
            context: .
            dockerfile: ./etc/docker/website/Dockerfile
        volumes:
            - ./src/website/public:/var/www/html

    site1-api:
        build:
            context: .
            dockerfile: ./etc/docker/website/Dockerfile
        volumes:
            - ./src/site1-api/public:/var/www/html

    site2-api:
        build:
            context: .
            dockerfile: ./etc/docker/website/Dockerfile
        volumes:
            - ./src/site2-api/public:/var/www/html

    site3-api:
        build:
            context: .
            dockerfile: ./etc/docker/website/Dockerfile
        volumes:
            - ./src/site3-api/public:/var/www/html

    nginx:
        image: nginx:latest
        ports:
            - "8080:80"
        depends_on:
            - website
            - site1-api
            - site2-api
            - site3-api
        volumes:
            - ./etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

