version: '2'

volumes:
    cache:
        driver: local
        driver_opts:
            type: tmpfs
            device: tmpfs
            o: uid=33
    logs:
        driver: local
        driver_opts:
            type: tmpfs
            device: tmpfs
            o: uid=33

services:

    website:
        build:
            dockerfile: /etc/docker/Dockerfile
            context: .
        volumes:
            - ./opt/php/dev/php.ini:/usr/local/etc/php/php.ini:ro
            - ./src:/var/www/html

    nginx:
        image: nginx:latest
        ports:
            - "8080:80"
        depends_on:
            - website
        volumes:
            - ./etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro

    composer:
        image: composer:latest
        volumes:
            - ./src:/app
        command: install