version: '2'

volumes:
    cache:
        driver: local
        driver_opts:
            type: tmpfs
            device: tmpfs
            o: uid=33
    logs:
        driver: local
        driver_opts:
            type: tmpfs
            device: tmpfs
            o: uid=33

services:

    website:
        build:
            context: .
            dockerfile: ./etc/docker/Dockerfile
        volumes:
            - ./src:/var/www/html

    nginx:
        image: nginx:latest
        ports:
            - "8080:80"
        depends_on:
            - website
        volumes:
            - ./etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro

